// Chapter12/web/frontend/components/button.component.ts
import { Component, Attribute, Input, Output, EventEmitter } from "@angular/core";

type Kind = "primary" | "secondary" | "success" |
            "danger" | "warning" | "info" | "light" |
            "dark" | "link";

@Component({
    selector: "app-button",
    template: `
        <button
            type="button"
            [class]="btnClass"
            (click)="click()"
        >
            <ng-content></ng-content>
        </button>`
})
export class ButtonComponent {

    public btnClass: string;
    @Output() public clicked = new EventEmitter();

    public constructor(
        @Attribute("kind") kind: Kind,
        @Attribute("className") className: string
    ) {
        this.btnClass = this._getBtnClass(kind, className);
    }

    private _getBtnClass(kind: Kind | null, className: string | null) {
        if (className) {
            return className;
        } else {
            const actualKind = kind ? kind : "primary";
            return `btn btn-${actualKind}`;
        }
    }

    public click() {
        this.clicked.emit();
    }

}

// Chapter11/web/frontend/components/button_component.tsx
import * as React from "react";

type Kind = "primary" | "secondary" | "success" |
            "danger" | "warning" | "info" | "light" |
            "dark" | "link";

interface ButtonProps {
    kind?: Kind;
    onClick(): void;
    className?: string;
}

export class Button extends React.Component<ButtonProps> {
    public render() {
        return (
            <button
                type="button"
                className={this._getClass()}
                onClick={() => this.props.onClick()}
            >
                {this.props.children}
            </button>
        );
    }
    private _getClass() {
        if (this.props.className !== undefined) {
            // If a class is specified we use it
            return this.props.className;
        } else {
            // If no class is specified we use the default "btn" with kind "primary"
            // If a kind is specified we use it
            const kind = this.props.kind ? this.props.kind : "primary";
            return `btn btn-${kind}`;
        }
    }
}
