// Chapter12/web/frontend/components/header.component.ts
import { Component, Input, Attribute } from "@angular/core";

type BgColor = "primary" | "secondary" | "success" |
               "danger" | "warning" | "info" | "light" |
               "dark" | "white";

export interface Route {
    label: string;
    path: string;
}

@Component({
    selector: "app-header",
    template: `
        <nav [ngClass]="navClass">
        <a class="navbar-brand" [routerLink]="rootPath" routerLinkActive="active">
            {{title}}
        </a>
        <ul class="navbar-nav">
            <li *ngFor="let link of links">
                <a class="navbar-brand" [routerLink]="link.path" routerLinkActive="active">
                    {{link.label}}
                </a>
            </li>
        </ul>
    </nav>`
})
export class HeaderComponent {

    public navClass!: string;
    public title!: string;
    public rootPath!: string;
    @Input() public links!: Route[];

    public constructor(
        @Attribute("bg") bg: BgColor,
        @Attribute("title") title: string,
        @Attribute("rootPath") rootPath: string,
    ) {
        this.navClass = `navbar navbar-expand-lg navbar-light bg-${bg}`;
        this.title = title;
        this.rootPath = rootPath;
    }
}

// Chapter11/web/frontend/components/header_component.tsx
import { Link } from "react-router-dom";
import * as React from "react";

type BgColor = "primary" | "secondary" | "success" |
               "danger" | "warning" | "info" | "light" |
               "dark" | "white";

interface HeaderProps {
    bg: BgColor;
    title: string;
    rootPath: string;
    links: { path: string; text: string }[];
}

export const Header = (props: HeaderProps) => (
    <nav className={`navbar navbar-expand-lg navbar-light bg-${props.bg}`}>
        <Link className="navbar-brand" to={props.rootPath}>
            {props.title}
        </Link>
        <ul className="navbar-nav">
            {
                props.links.map((link, linkIndex) => (
                    <Link
                        className="navbar-brand"
                        to={link.path}
                        key={linkIndex}
                    >
                        {link.text}
                    </Link>
                ))
            }
        </ul>
    </nav>
);
