// Chapter12/web/frontend/components/modal.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";

@Component({
    selector: "app-modal",
    template: `
        <div
            class="modal fade show"
            role="dialog"
            style="display: block"
        >
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">
                            {{title}}
                        </h5>
                        <app-button (clicked)="onCancel.emit()" [className]="'close'">
                            <span aria-hidden="true">&times;</span>
                        </app-button>
                    </div>
                    <div class="modal-body">
                        <div *ngIf="errorMsg">
                            <app-error [msg]="errorMsg"></app-error>
                        </div>
                        <ng-content></ng-content>
                    </div>
                    <div class="modal-footer">
                        <app-button (clicked)="onAccept.emit()">
                            {{acceptLabel}}
                        </app-button>
                        <app-button (clicked)="onCancel.emit()">
                            {{cancelLabel}}
                        </app-button>
                    </div>
                </div>
            </div>
        </div>
    `
})
export class ModalComponent {
    @Input() public title!: string;
    @Input() public acceptLabel!: string;
    @Input() public cancelLabel!: string;
    @Input() public error?: Error;
    @Output() public onCancel = new EventEmitter();
    @Output() public onAccept = new EventEmitter();
}

// Chapter11/web/frontend/components/modal_component.tsx
import * as React from "react";
import { Button } from "./button_component";
import { ErrorMsg } from "./error_msg_component";

interface ModalProps {
    title: string;
    isVisible: boolean;
    onAccept(): void;
    onAcceptLabel: string;
    onCancel(): void;
    onCancelLabel: string;
    error?: Error;
}

export class Modal extends React.Component<ModalProps> {
    public render() {
        if (!this.props.isVisible) {
            return null;
        } else {
            return (
                <div
                    className="modal fade show"
                    role="dialog"
                    style={{ display: "block" }}
                >
                    <div className="modal-dialog" role="document">
                        <div className="modal-content">
                            <div className="modal-header">
                                <h5 className="modal-title">
                                    {this.props.title}
                                </h5>
                                <Button
                                    className="close"
                                    onClick={() => {
                                        this.props.onCancel();
                                    }}
                                >
                                    <span aria-hidden="true">&times;</span>
                                </Button>
                            </div>
                            <div className="modal-body">
                                {
                                    (() => {
                                        if (this.props.error) {
                                            return <ErrorMsg msg={this.props.error.message} />;
                                        }
                                    })()
                                }
                                {this.props.children}
                            </div>
                            <div className="modal-footer">
                                <Button
                                    onClick={() => {
                                        this.props.onAccept();
                                    }}
                                >
                                    {this.props.onAcceptLabel}
                                </Button>
                                <Button
                                    kind="secondary"
                                    onClick={() => {
                                        this.props.onCancel();
                                    }}
                                >
                                    {this.props.onCancelLabel}
                                </Button>
                            </div>
                        </div>
                    </div>
                </div>
            );
        }
    }
}
