// Chapter11/web/frontend/pages/home_page.tsx
import * as React from "react";
import { Card } from "../components/card_component";
import { Container, Row, Column } from "../components/grid_component";

export const HomePage = () => (
    <Container>
        <Row>
            <Column width={6}>
                <Card
                    title="Movies"
                    description="Explore our database of movies"
                    linkPath="/movies"
                    linkText="Movies"
                    img={null}
                />
            </Column>
            <Column width={6}>
                <Card
                    title="Actors"
                    description="Explore our actors of movies"
                    linkPath="/actors"
                    linkText="Actors"
                    img={null}
                />
            </Column>
        </Row>
    </Container>
);

// Chapter12/web/frontend/pages/homepage.component.ts
import { Component } from "@angular/core";

@Component({
    selector: "home-page",
    template: `
        <app-container>
            <app-row>
                <app-column width="6">
                    <app-card
                        title="Movies"
                        description="Explore our database of movies"
                        linkPath="movies"
                        linkText="Movies"
                    ></app-card>
                </app-column>
                <app-column width="6">
                    <app-card
                        title="Actors"
                        description="Explore our actors of movies"
                        linkPath="actors"
                        linkText="Actors"
                    ></app-card>
                </app-column>
            </app-row>
        </app-container>
    `
})
export class HomePageComponent {
}
