// Chapter11/web/frontend/config/layout.tsx
import { Route, Switch, BrowserRouter } from "react-router-dom";
import * as React from "react";
import { Header } from "../components/header_component";
import { HomePage } from "../pages/home_page";
import { MoviePage } from "../pages/movies_page";
import { ActorPage } from "../pages/actors_page";
import "../stores/movie_store";
import "../stores/actor_store";

export const Layout = () => (
    <BrowserRouter>
        <div>
            <Header
                bg="primary"
                title="TsMovies"
                rootPath="/"
                links={[
                    { path: "/movies", text: "Movies"},
                    { path: "/actors", text: "Actors"}
                ]}
            />
            <main style={{ paddingTop: "60px" }}>
                <Switch>
                    <Route exact path="/" component={HomePage}/>
                    <Route path="/movies" component={MoviePage}/>
                    <Route path="/actors" component={ActorPage}/>
                </Switch>
            </main>
        </div>
    </BrowserRouter>
);

// Chapter12/web/frontend/config/layout.component.ts
import { Component, OnInit } from "@angular/core";
import { Route } from "../components/header.component";

@Component({
  selector: "app-layout",
  template: `
    <div>
        <app-header
            bg="primary"
            title="TsMovies"
            rootPath=""
            [links]="appRoutes"
        ></app-header>
        <main>
            <router-outlet></router-outlet>
        </main>
    </div>
  `
})
export class LayoutComponent {
    public appRoutes: Route[] = [
        { label: "Movies", path: "movies" },
        { label: "Actors", path: "actors" }
    ];
}
