// Chapter11/web/frontend/components/grid_component.tsx
import * as React from "react";

export class Container extends React.Component {
    public render() {
        return (
            <div className="container">
                {this.props.children}
            </div>
        );
    }
}

export class Row extends React.Component {
    public render() {
        return (
            <div className="row">
                {this.props.children}
            </div>
        );
    }
}

// In the bootstrap grid system the max size is 12
type ColumnWidth = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
type DeviceSize = "s" | "m" | "l" | "xl";

interface ColumnProps {
    width: ColumnWidth;
    size?: DeviceSize;
    style?: React.CSSProperties;
}

export class Column extends React.Component<ColumnProps> {
    public render() {
        return (
            <div className={this._getClass()} style={this.props.style ? this.props.style : {}}>
                {this.props.children}
            </div>
        );
    }
    private _getClass() {
        if (this.props.size !== undefined) {
            return `col-${this.props.size}-${this.props.width}`;
        } else {
            return `col-${this.props.width}`;
        }
    }
}

// Chapter12/web/frontend/components/grid.component.ts
import { Component, Attribute } from "@angular/core";

// In the bootstrap grid system the max size is 12
type ColumnWidth = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
type DeviceSize = "sm" | "md" | "lg" | "xl";

@Component({
    selector: "app-container",
    template: `
        <div class="container">
            <ng-content></ng-content>
        </div>
    `
})
export class ContainerComponent {}

@Component({
    host: {
        "[class]": "'row'"
    },
    selector: "app-row",
    template: `
        <ng-content></ng-content>
    `
})
export class RowComponent {}

@Component({
    host: {
        "[class]": "columnClass"
    },
    selector: "app-column",
    template: `
        <ng-content></ng-content>
    `
})
export class ColumnComponent {

    public columnClass: string;

    public constructor(
        @Attribute("width") width: ColumnWidth,
        @Attribute("size") size: DeviceSize | null,
    ) {
        this.columnClass = this._getClass(width, size);
    }

    private _getClass(width: ColumnWidth, size: DeviceSize | null) {
        if (size) {
            return `col-${size}-${width}`;
        } else {
            return `col-${width}`;
        }
    }
}
