// Chapter11/web/frontend/components/loading_component.tsx
import * as React from "react";

export class Loading extends React.Component {
    public render() {
        return (
            <div className="progress">
                <div
                    className="progress-bar progress-bar-striped progress-bar-animated"
                    role="progressbar"
                    style={{ width: "50%" }}
                >
                </div>
            </div>
        );
    }
}

// Chapter12/web/frontend/components/loading.component.ts
import { Component } from "@angular/core";

@Component({
    selector: "app-loading",
    template: `
        <div class="progress">
            <div
                class="progress-bar progress-bar-striped progress-bar-animated"
                role="progressbar"
                style="width: 50%"
            >
            </div>
        </div>`
})
export class LoadingComponent {
}
