// Chapter11/web/frontend/components/textfield_component.tsx
import * as React from "react";
import { ErrorMsg } from "./error_msg_component";

interface TextFieldProps {
    title: string;
    id: string;
    placeholder: string;
    value: any;
    isValid(value: any): boolean;
    onChange(value: string): void;
}

export class TextField extends React.Component<TextFieldProps> {
    public render() {
        return (
            <div>
                {this._renderError()}
                <div className="form-group">
                    <label>{this.props.title}</label>
                    <input
                        type="text"
                        className="form-control"
                        id={this.props.id}
                        placeholder={this.props.placeholder}
                        onKeyUp={(e) => this.props.onChange((e.target as any).value)}
                    />
                </div>
            </div>
        );
    }
    private _renderError() {
        if (!this.props.isValid(this.props.value)) {
            return (
                <ErrorMsg msg="Invalid input value!" />
            );
        }
    }
}

// Chapter12/web/frontend/components/textfield.component.ts
import { Component, EventEmitter, Input, Output } from "@angular/core";

@Component({
    selector: "app-text-field",
    template: `
        <div>
            <div *ngIf="errorMsg">
                <app-error [msg]="errorMsg"></app-error>
            </div>
            <div className="form-group">
                <label>{{title}}</label>
                <input
                    type="text"
                    className="form-control"
                    [id]="id"
                    [placeholder]="placeholder"
                    (input)="onEdit($event)"
                />
            </div>
        </div>
    `
})
export class TextFieldComponent {

    @Input() public title!: string;
    @Input() public id!: string;
    @Input() public placeholder!: string;
    @Input() public errorMsg!: null | string;
    @Output() public onChange = new EventEmitter<{k: string; v: string}>();

    public onEdit(event: any) {
        const value = (event.target as any).value;
        const key = (event.target as any).id;
        this.onChange.emit({ v: value, k: key });
    }

}
